GET http://localhost:8080/api/v1/question 

# Login

###

POST http://localhost:8080/api/v1/login
Content-Type: application/json

{
  "email":"Maverick43@yahoo.com",
  "password":"admin"
}


###

# protected route test
GET http://localhost:8080/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRGFtb24iLCJpYXQiOjE3MzQ5MTU3NTAsImV4cCI6MTczNDkxODE1MH0.uksWVpSzjdIxneLyBD_xD6KAT7xAO90fjRu1BYReyjg

# Dashboard Routes

### 

GET http://localhost:8080/dashboard/api/v1/questions/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRGFtb24iLCJpYXQiOjE3MzQ5MTU3NTAsImV4cCI6MTczNDkxODE1MH0.uksWVpSzjdIxneLyBD_xD6KAT7xAO90fjRu1BYReyjg
### 

GET http://localhost:8080/dashboard/api/v1/question/view/1ca268b1-02da-4ab9-81c3-6bf7913687ec
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRGFtb24iLCJpYXQiOjE3MzQ5MTU3NTAsImV4cCI6MTczNDkxODE1MH0.uksWVpSzjdIxneLyBD_xD6KAT7xAO90fjRu1BYReyjg


### 

GET http://localhost:8080/dashboard/api/v1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRGFtb24iLCJpYXQiOjE3MzQ5MTU3NTAsImV4cCI6MTczNDkxODE1MH0.uksWVpSzjdIxneLyBD_xD6KAT7xAO90fjRu1BYReyjg

###

POST http://localhost:8080/dashboard/api/v1/question/add
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRGFtb24iLCJpYXQiOjE3MzQ5MTU3NTAsImV4cCI6MTczNDkxODE1MH0.uksWVpSzjdIxneLyBD_xD6KAT7xAO90fjRu1BYReyjg
Content-Type: application/json

{
  "title":"Test title",
  "description":"desc",
  "alternativeA":"dad",
  "alternativeB":"fdsdfs",
  "alternativeC":"frwerfsd",
  "alternativeD":"fsf",
  "correctAlternative":"a"
}

###

PUT http://localhost:8080/dashboard/api/v1/question/edit/1ca268b1-02da-4ab9-81c3-6bf7913687ec
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRGFtb24iLCJpYXQiOjE3MzQ5MTU3NTAsImV4cCI6MTczNDkxODE1MH0.uksWVpSzjdIxneLyBD_xD6KAT7xAO90fjRu1BYReyjg
Content-Type: application/json

{
  "title":"meu carrinho branco"
}

###

DELETE  http://localhost:8080/dashboard/api/v1/question/delete/1ca268b1-02da-4ab9-81c3-6bf7913687ec
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRGFtb24iLCJpYXQiOjE3MzQ5MTU3NTAsImV4cCI6MTczNDkxODE1MH0.uksWVpSzjdIxneLyBD_xD6KAT7xAO90fjRu1BYReyjg